# DEFININDO AS VÁRIVEIS DA PA

# n1 PARA DECIDIR QUAL SERÁ O TERMO INICIAL DA PA
n1 = int(input("DIGITE O PRIMEIRO TERMO: "))

# r PARA DEFINIR A RAZÃO ENTRE OS TERMO (de quanto em quanto será pulado)
r = int(input(("DIGITE A RAZÃO: ")))

# n10 PARA DEFINIR O DÉCIMO TERMO DA PA
# ELE ESTÁ DE ACORDO COM A FÓRMULA DA PA
n10 = n1 + (10 - 1) * r

print(f"A PA DO NÚMERO {n1} ATÉ O DÉCIMO TERMO COM RAZÃO = {r} É:")


# FOR CRIADO PARA DETERMINAR A QUANTIDADE DE VEZES QUE O TERMO IRÁ APARECER, NO CASO É 10
# DEFINIMOS QUE OS PARÂMETROS DO RANGE SERÃO INSERIDOS PELO USUÁRIO (n1 e r)
# O "n10 + r" SERVE PARA DEFINIR O LIMITE DE TERMOS, NO CASO, 10 TERMOS
for c in range(n1, n10 + r, r):
    print(c, end=" -> ")
print("FINAL DA PA")




